name: grocery_app
description: "A Grocery App for fast delivery of the best fruits."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  flutter_screenutil: ^5.9.3
  icons_plus: ^5.0.0
  confetti: ^0.8.0
  dartz: ^0.10.1
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  shimmer: ^3.0.0
  lottie: ^3.3.1
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/fresh_fruits.png
    - assets/images/on_boarding_fruits.png
    - assets/images/on_boarding_delivery.png
    - assets/images/sign_up.png
    - assets/images/sign_in.png
    - assets/images/small_profile.png
    - assets/images/carousels/carousel_1.png
    - assets/images/carousels/carousel_2.png
    - assets/images/carousels/carousel_3.png
    - assets/images/carousels/carousel_4.png
    - assets/images/carousels/carousel_5.png
    - assets/images/carousels/carousel_6.png
    - assets/images/categories/category_1.png
    - assets/images/categories/category_2.png
    - assets/images/categories/category_3.png
    - assets/images/categories/category_4.png
    - assets/images/categories/category_5.png
    - assets/images/categories/category_6.png
    - assets/images/categories/category_7.png
    - assets/images/categories/category_8.png
    - assets/animations/favourite.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
